name: lolocal
favicon: null
layout_spectrum: 0.04150477587245405
typography_spectrum: 0.542224066099152
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.017175158951431513
  lightness: 0.8280306025408208
  saturation: 0.3811360648833215
  rhythmicContrast: 0.6930666274856776
purpose: []
