typography_spectrum: 0.542224066099152
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.4375
  lightness: 0.8280306025408208
  saturation: 0.3811360648833215
  rhythmicContrast: 0.6930666274856776
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.04150477587245405
analytics:
  google: null
  facebook: null
  twitter: null
name: lolocal
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: lolocal
purpose: []
